# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=60, unique=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=2083)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('user_agent', models.CharField(default=None, max_length=1024)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Redirect')),
            ],
            options={
                'ordering': ('updated_on',),
            },
        ),
    ]
