# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='user_agent',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
