# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170315_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='count',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='No of redirects'),
        ),
    ]
