# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_urldata_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
